services:
  stripe-cli-webhook:
    build:
      context: ./stripeCli
    ports:
      - "3000:3000"
    depends_on:
      - app-test
    networks:
      - app-network
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
  dotnet-test:
    build:
      context: ./ventaPeliculaWeb
    ports:
      - "7294:7294"
    depends_on:
      - app-test  # Asegura que app-test se inicie antes
    networks:
      - app-network
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}

  app-test:
    build:
      context: ./api
    ports:
      - "42069:42069"
    networks:
      - app-network
    environment:
      - PORT=42069
      - DATABASE_URL=${DATABASE_URL}
      - salt=11
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - type=${type}
      - project_id=${project_id}
      - private_key_id=${private_key_id}
      - private_key=${private_key}
      - client_email=${client_email}
      - client_id=${client_id}
      - auth_uri=${auth_uri}
      - token_uri=${token_uri}
      - auth_provider_x509_cert_url=${auth_provider_x509_cert_url}
      - client_x509_cert_url=${client_x509_cert_url}
      - universe_domain=${universe_domain}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - HCAPTCHA_SECRET=${HCAPTCHA_SECRET}


networks:
  app-network:
    driver: bridge
