#creamos la imagen
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

#restore
COPY ventaPeliculaWeb/ventaPeliculaWeb.csproj ventaPeliculaWeb/
RUN dotnet restore ventaPeliculaWeb/ventaPeliculaWeb.csproj

#build
COPY ventaPeliculaWeb/ ventaPeliculaWeb/
WORKDIR /src/ventaPeliculaWeb
RUN dotnet build ventaPeliculaWeb.csproj -c Release -o /app/build

#compilar
FROM build AS publish
RUN dotnet publish ventaPeliculaWeb.csproj -c Release -o /app/publish

#correr
FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 7294
WORKDIR /app
ENV ASPNETCORE_URLS=https://+:7294
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "ventaPeliculaWeb.dll" ]
