# USAMOS LA IMAGEN DE NODE 22
FROM node:22

# DIRECTORIO DE ACTIVO
WORKDIR /app

#package json
COPY package*.json ./
#instalamos las dependencias
RUN npm install
#copiamos todos los archivos
COPY . .

#definimos los args
ARG PORT 
ARG DATABASE_URL 
ARG salt 
ARG JWT_SECRET 
ARG JWT_REFRESH_SECRET 
ARG STRIPE_SECRET 
ARG type 
ARG project_id 
ARG private_key_id
ARG private_key 
ARG client_email 
ARG client_id 
ARG auth_uri 
ARG token_uri 
ARG auth_provider_x509_cert_url 
ARG client_x509_cert_url 
ARG universe_domain 
ARG STORAGE_BUCKET 
ARG WEBHOOK_SECRET 
ARG EMAIL_TOKEN 
ARG HCAPTCHA_SECRET

ARG CERTIFICATE_PASSWORD



# variables de entorno
ENV PORT=$PORT 
ENV DATABASE_URL=$DATABASE_URL 
ENV salt=$salt 
ENV JWT_SECRET=$JWT_SECRET 
ENV JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET 
ENV STRIPE_SECRET=$STRIPE_SECRET 
ENV type=$type 
ENV project_id=$project_id 
ENV private_key_id=$private_key_id 
ENV private_key=$private_key 
ENV client_email=$client_email 
ENV client_id=$client_id 
ENV auth_uri=$auth_uri 
ENV token_uri=$token_uri 
ENV auth_provider_x509_cert_url=$auth_provider_x509_cert_url 
ENV client_x509_cert_url=$client_x509_cert_url 
ENV universe_domain=$universe_domain 
ENV STORAGE_BUCKET=$STORAGE_BUCKET 
ENV WEBHOOK_SECRET=$WEBHOOK_SECRET 
ENV EMAIL_TOKEN=$EMAIL_TOKEN 
ENV HCAPTCHA_SECRET=$HCAPTCHA_SECRET

ENV CERTIFICATE_PASSWORD=$CERTIFICATE_PASSWORD



#exponemos el puerto
EXPOSE 42069
#corremos el proyecto
CMD ["npm", "start"]
